### ISSUE TITLE
Is tessWms source code still available?

### ISSUE THREAD

**Issue by Ziwei-Liu** [cstoeckert/cstoeckert.github.io#1]
I found TESS, a transcription element search tool, on your website, and found it no longer available for downloading. Then I followd the message on the web page and left this issue here. Is it still available to me to download the source code of tessWms? Thank you!

**Comment by cstoeckert** [comment]
I've uploaded the TESS_v1.0 folder [here](https://github.com/cstoeckert/cstoeckert.github.io/tree/main/past-projects/TESS_v1.0) and edited the TESS.md to reflect that.

**Comment by Ziwei-Liu** [comment]
> I've uploaded the TESS_v1.0 folder [here](https://github.com/cstoeckert/cstoeckert.github.io/tree/main/past-projects/TESS_v1.0) and edited the TESS.md to reflect that.

Thank you!
